CLASS ycl_cdd_recently_used_list DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
        DATA items TYPE STANDARD TABLE OF STRING
     WITH EMPTY KEY.

  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS YCL_CDD_RECENTLY_USED_LIST IMPLEMENTATION.
ENDCLASS.
